global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "email"
        from: "email"
        smarthost: smtp.gmail.com:587
        auth_username: "email"
        auth_password: "mot_passe_application_google"
        headers:
          Subject: "[ALERTE] {{ .GroupLabels.alertname }}"
